apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: laya-model-cache
  namespace: laya-demo
  labels:
    app.kubernetes.io/part-of: laya-demo
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: laya-gpu-cache
  namespace: laya-demo
  labels:
    app.kubernetes.io/part-of: laya-demo
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: laya-playground-cache
  namespace: laya-demo
  labels:
    app.kubernetes.io/part-of: laya-demo
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 10Gi
